sudo: false
language: node_js
notification:
  email: false
cache:
  directories:
    - ~/.npm
node_js: "lts/*"
branches:
  only:
    - master
install: npm install
script:
  - npm run lint
  - npm run test-coverage
  - npm run packaging
after_success: npx codecov
